#!/bin/bash

#SBATCH --mem=16G
#SBATCH --time=1:00:00

module load fsl/6.0.6

sub_list="/well/miller/users/uai965/UKBB/Subjects_400/G"
core_path="/well/miller/users/uai965/UKBB/Subjects_400"

NAWM_Output="/well/miller/users/uai965/UKBB/Subjects400/NAWM_AD_Output.csv"
WMH_Output="/well/miller/users/uai965/UKBB/Subjects_400/WMH_AD_Output.csv"

echo "ID,Mean_AD_NAWM_Deep" > $D_Output
echo "ID,Mean_AD_WMH_Peri" > $P_Output

while read -r ID; do

	AD="${core_path}/${ID}/dMRI/dMRI/dti_L1.nii.gz"
	P="${core_path}/${ID}/T2_FLAIR/lesions/output/peri_final_mask_no_diff_3.nii.gz"
	D="${core_path}/${ID}/T2_FLAIR/lesions/output/deep_final_mask_no_diff_3.nii.gz"

	echo "${ID},$(fslstats ${AD} -k ${D} -M)" >> $D_Output
	echo "${ID},$(fslstats ${AD} -k ${P} -M)" >> $P_Output

	echo "WMH AD and NAWM AD have been extracted for ${ID}"
done < "$sub_list"

echo "Done"
