#!/bin/bash

#SBATCH --mem=16G
#SBATCH --time=1:00:00

module load fsl/6.0.6

sub_list="/well/miller/users/uai965/UKBB/Subjects_100/sub_list_100"
core_path="/well/miller/users/uai965/UKBB/Subjects_100"

NAWM_Output="/well/miller/users/uai965/UKBB/Subjects_100/NAWM_AD_Output.csv"
WMH_Output="/well/miller/users/uai965/UKBB/Subjects_100/WMH_AD_Output.csv"

echo "ID,Mean_AD_NAWM" > $NAWM_Output
echo "ID,Mean_AD_WMH" > $WMH_Output

while read -r ID; do

	AD="${core_path}/${ID}/dMRI/dMRI/dti_L1.nii.gz"
        WMH_NO_DIF_3_bin="${core_path}/${ID}/T2_FLAIR/lesions/output/final_mask_no_diff_3_bin.nii.gz"
	NAWM_bin="${core_path}/${ID}/T2_FLAIR/lesions/output/NAWM_bin.nii.gz"

	echo "${ID},$(fslstats ${AD} -k ${NAWM_bin} -M)" >> $NAWM_Output
	echo "${ID},$(fslstats ${AD} -k ${WMH_NO_DIF_3_bin} -M)" >> $WMH_Output

	echo "WMH AD and NAWM AD have been extracted for ${ID}"
done < "$sub_list"

echo "Done"
