#!/bin/bash

module load fsl/6.0.6

core_path="/well/miller/users/uai965/UKBB/Subjects_400"
sub_list="$core_path/G"

XTRACT_ROI_list="/well/miller/users/uai965/UKBB/Subjects_100/XTRACT_List"

while read -r ID; do

        NODIF="$core_path/${ID}/dMRI/dMRI/nodif_brain.nii.gz"
        WARP="$core_path/${ID}/dMRI/dMRI/std2diff_warp.nii.gz"

	while read -r ROI; do

	ROI="$core_path/${ID}/dMRI/autoptx_preproc/tracts/${ROI}/tracts/tractsNorm_001_bin.nii.gz"
	ROI_in_NODIF="$core_path/${ID}/dMRI/autoptx_preproc/tracts/${ROI}/tracts/tractsNorm_001_bin_in_dif.nii.gz"

	applywarp -i "${ROI}" -r "${NODIF}" -o "${ROI_in_NODIF}" -w "${WARP}"

	echo "Warped ${ROI} for ${ID}"
	done < "$ROI_list"

	echo "Done all ROIs for ${ID}"

done < "$sub_list"

echo "DONE"
