#!/bin/bash

module load fsl/6.0.6

core_path="/well/miller/users/uai965/UKBB/Subjects_400"
sub_list="$core_path/G"

while read -r ID; do

	NO_DIF="${core_path}/${ID}/dMRI/dMRI/nodif_brain.nii.gz"
	FLAIR_in_NO_DIF_M="${core_path}/${ID}/T2_FLAIR/Flair_to_NO_DIF.mat"
	WMH_D="${core_path}/${ID}/T2_FLAIR/lesions/pwmh_dwmh_output/deepwm_map_10mm.nii.gz"
	WMH_D_NO_DIF="${core_path}/${ID}/T2_FLAIR/lesions/output/deep_final_mask_no_diff.nii.gz"
	WMH_D_NO_DIF_3="${core_path}/${ID}/T2_FLAIR/lesions/output/deep_final_mask_no_diff_3.nii.gz"
        WMH_P="${core_path}/${ID}/T2_FLAIR/lesions/pwmh_dwmh_output/perivent_map_10mm.nii.gz"
        WMH_P_NO_DIF="${core_path}/${ID}/T2_FLAIR/lesions/output/peri_final_mask_no_diff.nii.gz"
        WMH_P_NO_DIF_3="${core_path}/${ID}/T2_FLAIR/lesions/output/peri_final_mask_no_diff_3.nii.gz"

	flirt -in "${WMH_D}" -ref "${NO_DIF}" -applyxfm -init "${FLAIR_in_NO_DIF_M}" -out "${WMH_D_NO_DIF}" -interp trilinear
	flirt -in "${WMH_P}" -ref "${NO_DIF}" -applyxfm -init "${FLAIR_in_NO_DIF_M}" -out "${WMH_P_NO_DIF}" -interp trilinear

	echo "WMH_D and WMH_P have been moved to nodif"

	fslmaths "${WMH_D_NO_DIF}" -thr 0.3 "${WMH_D_NO_DIF_3}"
        fslmaths "${WMH_P_NO_DIF}" -thr 0.3 "${WMH_P_NO_DIF_3}"

	echo "WMH_D and _P has been moved and thresholded for ${ID}"
done < "$sub_list"

echo "done"
