#!/bin/bash

core_path="/path/to/project/directory"
sub_list="${core_path}/sub_list"
MNI_path="/path/to/MNI152_T1_2mm.nii.gz"

while read -r ID; do
    lesion_mask="${core_path}/${ID}/T2_FLAIR/lesions/output/lesion_mask_resampled.nii.gz"
    output_dir="${core_path}/${ID}/T2_FLAIR/lesions/output"

    fslmaths "${lesion_mask}" -kernel sphere 2 -fmean "${output_dir}/lesion_mask_resampled__sphere_2.nii.gz"
    fslmaths "${lesion_mask}" -kernel sphere 5 -fmean "${output_dir}/lesion_mask_resampled__sphere_5.nii.gz"
    fslmaths "${lesion_mask}" -kernel sphere 8 -fmean "${output_dir}/lesion_mask_resampled__sphere_8.nii.gz"
    fslmaths "${lesion_mask}" -kernel sphere 10 -fmean "${output_dir}/lesion_mask_resampled__sphere_10.nii.gz"

    echo "Sphere masks have been made at 2mm and 5mm for ${ID}"

    done < "$sub_list"

echo "A sphere mask has been made at 2mm and 5mm for all participants"
