#!/bin/bash

module load fsl/6.0.6

core_path="/path/to/project/directory"
sub_list="${core_path}/sub_list"
MNI_path="/path/to/MNI152_T1_2mm.nii.gz"

while read -r ID; do
    lesion_mask="${core_path}/${ID}/T2_FLAIR/lesions/output/lesion_mask_resampled_bin.nii.gz"
    output_dir="${core_path}/${ID}/T2_FLAIR/lesions/output"

    fslmaths "${output_dir}/lesion_mask_resampled__sphere_2.nii.gz" -bin "${output_dir}/lesion_mask_resampled__sphere_2_bin.nii.gz"
    fslmaths "${output_dir}/lesion_mask_resampled__sphere_5.nii.gz" -bin "${output_dir}/lesion_mask_resampled__sphere_5_bin.nii.gz"
    fslmaths "${output_dir}/lesion_mask_resampled__sphere_8.nii.gz" -bin "${output_dir}/lesion_mask_resampled__sphere_8_bin.nii.gz"
    fslmaths "${output_dir}/lesion_mask_resampled__sphere_10.nii.gz" -bin "${output_dir}/lesion_mask_resampled__sphere_10_bin.nii.gz"

    fslmaths "${output_dir}/lesion_mask_resampled__sphere_2_bin.nii.gz" -sub "${lesion_mask}" "${output_dir}/lesion_mask_resampled__sphere_2_NL.nii.gz"
    fslmaths "${output_dir}/lesion_mask_resampled__sphere_5_bin.nii.gz" -sub "${lesion_mask}" "${output_dir}/lesion_mask_resampled__sphere_5_NL.nii.gz"
    fslmaths "${output_dir}/lesion_mask_resampled__sphere_8_bin.nii.gz" -sub "${lesion_mask}" "${output_dir}/lesion_mask_resampled__sphere_8_NL.nii.gz"
    fslmaths "${output_dir}/lesion_mask_resampled__sphere_10_bin.nii.gz" -sub "${lesion_mask}" "${output_dir}/lesion_mask_resampled__sphere_10_NL.nii.gz"

    echo "Sphere masks have been lesion extracted for ${ID}"

    done < "$sub_list"

echo "Sphere masks have been lesion extracted for all participants"
