#!/bin/bash

module load fsl/6.0.6

core_path="/path/to/project/directory"
sub_list="${core_path}/sub_list"
JHU_ROI_Path="/path/to/ROIs_JHU"
JHU_ROI_list="${JHU_ROI_Path}/ROI_JHU_List"
MNI_path="/path/to/MNI152_T1_2mm.nii.gz"

while read -r ID; do
    output_dir="${core_path}/${ID}/T2_FLAIR/lesions/output"
    
    while read -r ROI; do
        fslmaths "${output_dir}/${ID}_${ROI}_thresholded_output.nii.gz" -bin "${output_dir}/${ID}_${ROI}_thresholded_output_bin.nii.gz"
        fslmaths "${output_dir}/${ROI}_resampled.nii.gz" -sub "${output_dir}/${ID}_${ROI}_thresholded_output_bin.nii.gz" "${output_dir}/${ROI}_NL.nii.gz"       

    done < "$JHU_ROI_list"

    echo "Lesions have been extracted for each WM ROI for ${ID}"
done < "$sub_list"

echo "Lesions have been extracted for each WM ROI for all participants"
