#!/bin/bash

core_path="/path/to/project/directory"
sub_list="${core_path}/sub_list"

JHU_ROI_Path="/path/to/ROIs_JHU"
JHU_ROI_list="${JHU_ROI_Path}/ROI_JHU_List"
MNI_path="/path/to/MNI152_T1_2mm.nii.gz"

while read -r ID; do
    lesion_mask="${core_path}/${ID}/T2_FLAIR/lesions/final_mask_to_MNI.nii.gz"
    output_dir="${core_path}/${ID}/T2_FLAIR/lesions/output"
    
    mkdir -p "$output_dir"

    flirt -in "${lesion_mask}" -ref "${MNI_path}" -out "${output_dir}/lesion_mask_resampled.nii.gz" -applyisoxfm 2

    while read -r ROI; do
        ROI_file="${JHU_ROI_Path}/${ROI}.nii.gz"
        flirt -in "${ROI_file}" -ref "${output_dir}/lesion_mask_resampled.nii.gz" -out "${output_dir}/${ROI}_resampled.nii.gz" -applyisoxfm 2
        fslmaths "${output_dir}/lesion_mask_resampled.nii.gz" -mas "${output_dir}/${ROI}_resampled.nii.gz" "${output_dir}/${ID}_${ROI}_thresholded_output.nii.gz"
    done < "$JHU_ROI_list"

    echo "Lesion mask has been thresholded for all WM ROIs for $ID"
done < "$sub_list"

echo "Lesion mask has been thresholded for all ROIs for all participants"
