#!/bin/bash

#SBATCH --mem=16G
#SBATCH --time=1:00:00

module load fsl/6.0.6

core_path="/well/miller/users/uai965/UKBB/Subjects_400"
sub_list="$core_path/G"

while read -r ID; do

    M1="${core_path}/${ID}/T2_FLAIR/lesions/output/lesion_mask_sphere_1_b.nii.gz"
    M2="${core_path}/${ID}/T2_FLAIR/lesions/output/lesion_mask_sphere_2_b.nii.gz"
    M3="${core_path}/${ID}/T2_FLAIR/lesions/output/lesion_mask_sphere_3_b.nii.gz"
    M4="${core_path}/${ID}/T2_FLAIR/lesions/output/lesion_mask_sphere_4_b.nii.gz"
    M5="${core_path}/${ID}/T2_FLAIR/lesions/output/lesion_mask_sphere_5_b.nii.gz"

    M1_0="${core_path}/${ID}/T2_FLAIR/lesions/output/lesion_mask_sphere_1_0"
    M2_1="${core_path}/${ID}/T2_FLAIR/lesions/output/lesion_mask_sphere_2_1.nii.gz"
    M3_12="${core_path}/${ID}/T2_FLAIR/lesions/output/lesion_mask_sphere_3_12.nii.gz"
    M4_123="${core_path}/${ID}/T2_FLAIR/lesions/output/lesion_mask_sphere_4_123.nii.gz"
    M5_1234="${core_path}/${ID}/T2_FLAIR/lesions/output/lesion_mask_sphere_5_1234.nii.gz"

    # Create ring masks
    fslmaths "${M1}" -sub "${core_path}/${ID}/T2_FLAIR/lesions/output/final_mask_no_diff_3.nii.gz" "${M1_0}"
    fslmaths "${M2}" -sub "${M1}" "${M2_1}"
    fslmaths "${M3}" -sub "${M2_1}" "${M3_12}"
    fslmaths "${M4}" -sub "${M3_12}" "${M4_123}"
    fslmaths "${M5}" -sub "${M4_123}" "${M5_1234}"

    echo "NAWM AD at 1mm–5mm has been extracted for ${ID}"

done < "$sub_list"

echo "Done"
