#!/bin/bash
module load fsl/6.0.6

core_path="/well/miller/users/uai965/UKBB/Subjects_400"
sub_list="$core_path/G"

while read -r ID; do
    lesion_mask="${core_path}/${ID}/T2_FLAIR/lesions/output/final_mask_no_diff_3.nii.gz"
    output_dir="${core_path}/${ID}/T2_FLAIR/lesions/output"

    fslmaths "${lesion_mask}" -kernel sphere 1 -fmean "${output_dir}/lesion_mask_sphere_1.nii.gz"    
    fslmaths "${lesion_mask}" -kernel sphere 2 -fmean "${output_dir}/lesion_mask_sphere_2.nii.gz"
    fslmaths "${lesion_mask}" -kernel sphere 3 -fmean "${output_dir}/lesion_mask_sphere_3.nii.gz"
    fslmaths "${lesion_mask}" -kernel sphere 4 -fmean "${output_dir}/lesion_mask_sphere_4.nii.gz"    
    fslmaths "${lesion_mask}" -kernel sphere 5 -fmean "${output_dir}/lesion_mask_sphere_5.nii.gz"    

    echo "Sphere masks have been made at 1mm - 5mm for ${ID}"

    done < "$sub_list"

echo "A sphere mask has been made at 1mm - 5mm for all participants"
