#!/bin/bash

module load fsl/6.0.6

core_path="/path/to/data"
sub_list="/path/to/data/sub_list"

while read -r ID; do

	mkdir -p "$core_path/${ID}/T2_FLAIR/lesions/output"

	FLAIR="${core_path}/${ID}/T2_FLAIR/T2_FLAIR_brain.nii.gz"
	NO_DIF="${core_path}/${ID}/dMRI/dMRI/nodif_brain.nii.gz"
	FLAIR_in_NO_DIF="${core_path}/${ID}/T2_FLAIR/Flair_to_NO_DIF.nii.gz"
	FLAIR_in_NO_DIF_M="${core_path}/${ID}/T2_FLAIR/Flair_to_NO_DIF.mat"
	WMH="${core_path}/${ID}/T2_FLAIR/lesions/final_mask.nii.gz"
	WMH_NO_DIF="${core_path}/${ID}/T2_FLAIR/lesions/output/final_mask_no_diff.nii.gz"
	WMH_NO_DIF_3="${core_path}/${ID}/T2_FLAIR/lesions/output/final_mask_no_diff_3.nii.gz"

	flirt -in "${FLAIR}" -ref "${NO_DIF}" -out "${FLAIR_in_NO_DIF}" -omat "${FLAIR_in_NO_DIF_M}" -dof 6
	flirt -in "${WMH}" -ref "${NO_DIF}" -applyxfm -init "${FLAIR_in_NO_DIF_M}" -out "${WMH_NO_DIF}" -interp trilinear
	fslmaths "${WMH_NO_DIF}" -thr 0.3 "${WMH_NO_DIF_3}"

	echo "WMH has been moved to dif space and thresholded for ${ID}"

done < "$sub_list"

echo "done"
