#!/bin/bash

module load fsl/6.0.6

core_path="/path/to/project/directory"
sub_list="${core_path}/sub_list"

JHU_ROI_Path="/path/to/ROIs_JHU"
JHU_ROI_list="${JHU_ROI_Path}/ROI_JHU_List"

while read -r ID; do
    dist_lesion_mask="${core_path}/${ID}/T2_FLAIR/lesions/output/distance_map_lesion_mask_resampled.nii.gz"
    output_dir="${core_path}/${ID}/T2_FLAIR/lesions/output"
    
    mkdir -p "$output_dir"
    
    while read -r ROI; do
        ROI_file="${output_dir}/${ROI}_NL.nii.gz"
	fslmaths "${dist_lesion_mask}" -mas "${ROI_file}" "${output_dir}/${ROI}_NL_distance_map_thresholded_output.nii.gz"
    done < "$JHU_ROI_list"
    echo "All WM ROIs (after lesion extraction) have been masked by the distance map for ${ID}"
done < "$sub_list"
echo "All WM ROIs have been masked by the distance map for all participants"
