#!/bin/bash

module load fsl/6.0.6

core_path="/path/to/project/directory"
sub_list="${core_path}/sub_list"

while read -r ID; do
  ERO_WM_Mask="${core_path}/${ID}/T1/T1_fast/WM_mask_ero.nii.gz"
	NO_DIF="${core_path}/${ID}/dMRI/dMRI/nodif_brain.nii.gz"
	ERO_WM_NO_DIF="${core_path}/${ID}/T1/T1_fast/ERO_WM_to_NO_DIF.nii.gz"
	ERO_WM_NO_DIF_M="${core_path}/${ID}/T1/T1_fast/ERO_WM_to_NO_DIF.mat"
	ERO_WM_NO_DIF_05="${core_path}/${ID}/T1/T1_fast/ERO_WM_to_NO_DIF_05.nii.gz"
	WMH_NO_DIF_3="${core_path}/${ID}/T2_FLAIR/lesions/output/final_mask_no_diff_3.nii.gz"
        WMH_NO_DIF_3_bin="${core_path}/${ID}/T2_FLAIR/lesions/output/final_mask_no_diff_3_bin.nii.gz"
	NAWM="${core_path}/${ID}/T2_FLAIR/lesions/output/NAWM.nii.gz"
	NAWM_bin="${core_path}/${ID}/T2_FLAIR/lesions/output/NAWM_bin.nii.gz"

	#Move ero WM mask into no dif space

	flirt -in "${ERO_WM_Mask}" -ref "${NO_DIF}" -out "${ERO_WM_NO_DIF}" -omat "${ERO_WM_NO_DIF_M}" -dof 6

	#Ensure only WM voxels are included by thresholding 0.5

	fslmaths "${ERO_WM_NO_DIF}" -thr 0.5 "${ERO_WM_NO_DIF_05}"

	#Binarize WMH mask

	fslmaths "${WMH_NO_DIF_3}" -bin "${WMH_NO_DIF_3_bin}"

	#Subtract WMH mask from WM mask (to get remaining NAWM)

	fslmaths "${ERO_WM_NO_DIF_05}" -sub "${WMH_NO_DIF_3_bin}" "${NAWM}"

	#Binarize

	fslmaths "${NAWM}" -bin "${NAWM_bin}"

	echo "WMH has been moved and thresholded for ${ID}"
done < "$sub_list"

echo "Done"
